name: armTemplateDeployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  location: westus3
  # Network Sandbox
  subscriptionID: 17df786b-c9ea-4f50-9cb0-57b80e526f55
  networkResourceGroup: sfc-network-dev-rg__

jobs:
  armDeployResourceGroup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_NETWORK_SANDBOX }}

      - name: deploy-resource-group-template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionID: ${{ env.subscription_id}}
          region: ${{ env.location}}
          template: ./rg.json
          parameters: ./rg.parameters.json
          deploymentName: resourcegroup

  armDeployMainTemplate:
    runs-on:  ubuntu-latest
    needs:  armDeployResourceGroup
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_NETWORK_SANDBOX }}

      - name: deploy-main-template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName:  ${{ env.networkResourceGroup }}
          subscriptionID: ${{ env.subscription_id}}
          region: ${{ env.location}}
          template: ./main.json
          parameters: ./main.parameters.json
          deploymentName: main  