name: armTemplateDeployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - '*rework'
      - '*devel'
  workflow_dispatch:

env:
  location: westus3
  # Network Sandbox
  subscriptionID: 17df786b-c9ea-4f50-9cb0-57b80e526f55
  networkResourceGroupName: sfc-network-dev-rg_
  resourceGroupName: sfc-firewalltest-dev-rg_

jobs:
  deployResourceGroup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_NETWORK_SANDBOX }}

      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            # set account
            az account set -s 'Network Sandbox'
            az group create -n ${{ env.resourceGroupName }} -l ${{ env.location }}
            az group create -n ${{ env.networkResourceGroupName }} -l ${{ env.location }}
            echo "Azure resource groups created"

  armDeployMainTemplate:
    runs-on:  ubuntu-latest
    needs:  deployResourceGroup
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL_NETWORK_SANDBOX }}

      - name: deploy-main-template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName:  ${{ env.resourceGroupName }}
          subscriptionID: ${{ env.subscription_id}}
          region: ${{ env.location}}
          template: ./main.json
          parameters: ./main.parameters.json adminPassword=${{ secrets.WIN_10_ADMIN_PASSWORD }}
          deploymentName: main  
